### ISSUE TITLE
show scrollbar on the blog site

### ISSUE THREAD

**Issue by mackuba** [bluesky-social/atproto-website#106]
Hey, I'm not sure where to report this, because I think the blog is in a different repo (private one probably), but could you please change the style on the blog so that the scrollbar shows up? I don't know which stylesheet line it is specifically, but something must be explicitly hiding the scrollbar because otherwise it would be displayed normally by default. I don't know what the intention was, but this makes it confusing because you don't know at what position you are in relation to the whole document and how much more you have to read when scrolling through a blog post.

**Comment by flyingRa1jin** [comment]
Hi @mackuba, I am able to see the scroll in the website dev blog. The issue looks fixed to me. Please correct me if I'm wrong.

**Comment by mackuba** [comment]
I'm talking about this one:

<img width="800" alt="Screen Shot 2023-09-17 at 19 21 37" src="https://github.com/bluesky-social/atproto-website/assets/28465/e22e5a30-2b4f-4dc3-8485-d1159ae7ec84">

**Comment by bnewbold** [comment]
I think the current version of the company blog (eg, https://bsky.social/about/blog/09-04-2024-welcome) now has this. Please re-open if it isn't working for you.
