### ISSUE TITLE
Clarify "72 hour window"

### ISSUE THREAD

**Issue by makoConstruct** [bluesky-social/atproto-website#15]
https://atproto.com/guides/overview

> Signing key: Asserts changes to the DID Document and to the user's data repository.
> Recovery key: Asserts changes to the DID Document; may override the signing key within a **72-hour window**.

This description of what the recovery key does is completely unclear. What acts can it override? What happens at the end of the time window? As a reader, as far as I'm aware at this stage in the document, everything we'd do with the signing key happens instantly, and doesn't have a time window. I think it has to be explained what operations this window applies to.

**Comment by dholms** [comment]
Yup thanks for the feedback. I actually just did some work revamping PLC & we're going to give all the docs a revamp soon 👍 

A recovery key can "fork history" & the PLC server will side with its fork over the signing key's fork.

So if a signing key "attacks" my did by trying to rotate it away from me, I have a 72 hour window during which I can create a new operation that overrides that operation. 

It can override any operation that alters the did document. If the signing key was making bad commits to the repo, then the recovery key will need to update the did document to take control away from the signing key, then rewrite & rebase repo history to return it to a good state.

**Comment by makoConstruct** [comment]
That clarifies a lot, but I don't know what a PLC is.

(Will close when I see the new overview, looking forward to reading it.)

**Comment by dholms** [comment]
More on PLC here: https://atproto.com/specs/did-plc

**Comment by bnewbold** [comment]
Documentation of the DID PLC method has moved over to here: https://github.com/bluesky-social/did-method-plc

Going to close this issue here; if you have more questions please do re-open over in the other repo!
