### ISSUE TITLE
Modified import statement to module path aliases

### ISSUE THREAD

**Issue by ryohidaka** [bluesky-social/atproto-website#16]
## Overview
Modified import statement of JSX files to `module path aliases`.

## Why
This was addressed because each time the directory gets deeper, the import minute gets longer.

## Docs
https://nextjs.org/docs/advanced-features/module-path-aliases

**Comment by Harmonygrams** [comment]
Please assign to me. I can work on this.

**Comment by bnewbold** [comment]
I think the recent refactor of the website covered this. Please re-open if still an issue!
