### ISSUE TITLE
Lexicon links 404

### ISSUE THREAD

**Issue by neema-orual** [bluesky-social/atproto-website#199]
Might not be the right place to inform, but https://atproto.com/lexicons/app-bsky-feed#post and other links on the ATProto docs site seem to be 404-ing currently.
![Screenshot for reference, just in case](https://github.com/bluesky-social/atproto-website/assets/119020340/482f1ba8-8130-4bf8-b98e-25cfb3603398)

**Comment by bnewbold** [comment]
I think I hunted all these down; please re-open if you find any that are still broken.
