### ISSUE TITLE
Add the lexicons

### ISSUE THREAD

**Issue by pfrazee** [bluesky-social/atproto-website#2]

**Comment by myConsciousness** [comment]
Hi @pfrazee ,

I have noticed the presence of some Lexicons not reflected in documents. And I have already forked this repository and found the fixes, but I realized from the following comments that they may have been auto-generated.

```markdown
<!-- START lex generated content. Please keep comment here to allow auto update -->
<!-- DON'T EDIT THIS SECTION! INSTEAD RE-RUN lex TO UPDATE -->

<!-- END lex generated TOC please keep comment here to allow auto update -->
```

What is `lex`? And can I run this program?

**Comment by myConsciousness** [comment]
@pfrazee ,

Okay, I found this generator :)

https://github.com/bluesky-social/atproto/tree/4c346d201742d6f76ed166cb0704fbfed2f372df/packages/lex-cli

**Comment by pfrazee** [comment]
Hey yep, this issue is still open because we need to automate the generation to stay in sync, _and_ because the website doc is currently not super useful yet. We plan to spend some time soon improving this

**Comment by myConsciousness** [comment]
@pfrazee ,

I see! It seemed to me that generating the documentation for these Lexicons and deploying them to the website could be automated even with GitHub Actions.

Anyway so excited to see this project develop!

**Comment by bnewbold** [comment]
we've got another plan in the works for this
