### ISSUE TITLE
Broken Lexicon links on documentation overview pgae

### ISSUE THREAD

**Issue by MikeBeas** [bluesky-social/atproto-website#26]
On https://atproto.com/guides/overview#interoperation there are two links, "ATP Lexicon" and "Bsky Lexicon" which are returning 404. They appear to have led to `/lexicons/atproto-com` and `/lexicons/bsky-app` at some point but both of those links are now missing.

Looking at the sidebar it looks like there aren't overview pages for the atproto and bsky lexicons, so I'm not sure where these are intended to link.

**Comment by thinkverse** [comment]
See https://github.com/bluesky-social/atproto-website/pull/24 👍

**Comment by MikeBeas** [comment]
Ah, I specifically went looking for related issues before filing this one and still missed that one somehow. Thanks, I'll close this one.
