### ISSUE TITLE
Fix styling on `/lexicons/*`

### ISSUE THREAD

**Issue by pablo-clueless** [bluesky-social/atproto-website#32]
![Screenshot_20230423_093312_Chrome.jpg](https://user-images.githubusercontent.com/68032187/233829089-a13ea328-29a7-4a1e-bc90-2785d9d43f06.jpg)

## Issue
Some of the headings in the lexicons extend beyond the viewport and cause an overflow. This can easily be fixed by wrapping the text, breaking it, or reducing font size(not optimal)

**Comment by manusudha** [comment]
is this issue is still open @pablo-clueless if yes can i work on that .

**Comment by bnewbold** [comment]
This has been addressed on atproto.com by turning these in to github links, and we are planning to soon move most lexicon documentation to a new site as well.
