### ISSUE TITLE
"Applications" guide doesn't show up under the "Guides" menu

### ISSUE THREAD

**Issue by mbernardes19** [bluesky-social/atproto-website#336]
This page doesn't appear under the "Guides" section on the sidebar: https://atproto.com/guides/applications

Due to that, the applications guide is only accessible through the URL.

<img width="1428" alt="Screenshot 2024-09-10 at 12 18 12" src="https://github.com/user-attachments/assets/2cfdf88b-f29c-4213-8d7b-a6f61ff26472">

**Comment by bnewbold** [comment]
It is the "Building apps" -> "Quick start" link in the toolbar, indicated by the blue bar, not in the "Guides" section.

**Comment by mbernardes19** [comment]
@bnewbold Oh thanks, hadn't seen that. Was mistaken by the "/guides" parent path, and didn't even notice the active style on the item haha.
