### ISSUE TITLE
Broken Hyperlink

### ISSUE THREAD

**Issue by ptrlrd** [bluesky-social/atproto-website#44]
The application guides, specifically the signing-in section is currently referencing to a page that does not exist.

The paragraph that has the link: https://atproto.com/guides/applications#signing-in
The hyperlink: https://atproto.com/lexicons/com-atproto-session

The exact line where the 404 is
https://github.com/bluesky-social/atproto-website/blob/a3081a7fe87a1e04b250f9357aaf90e585fc95c5/content/guides/applications.md?plain=1#L18

**Comment by thinkverse** [comment]
Created a PR with a potential fix, we'll see what the bsky team says.
