### ISSUE TITLE
Broken /lexicons/com-atproto-handle hyperlink

### ISSUE THREAD

**Issue by glenjarvis** [bluesky-social/atproto-website#46]
This is similar (but different than issue #44). It's a different hyperlink.

Page: https://atproto.com/guides/identity

Paragraph:
> Handles are DNS names. They are resolved using the com.atproto.identity.resolveHandle() XRPC method and should be confirmed by a matching entry in the DID document.

Broken Link: https://atproto.com/lexicons/com-atproto-handle

**Comment by smanask** [comment]
I've created a PR with the potential fixes, let's wait for the team to verify and merge.

**Comment by bnewbold** [comment]
This seems to have been fixed!
