### ISSUE TITLE
Guide and spec are inconsistent in defining `LexiconDoc`

### ISSUE THREAD

**Issue by nathan-at-least** [bluesky-social/atproto-website#51]
For fun I'm writing a parser for lexicons while following the guide at https://atproto.com/guides/lexicon which I believe is rendered from this repository.

I paused to write this ticket to glance at PR and found https://github.com/bluesky-social/atproto-website/pull/29 which updates the lexicon _spec_ (in contrast to the guide).

So them I went back to compare the spec to the guide in the main branch and it appears they're inconsistent.

From [the guide](https://github.com/bluesky-social/atproto-website/blob/main/content/guides/lexicon.md?plain=1#L44-L61) it introduces `LexiconDoc` as:

```
interface LexiconDoc {
  lexicon: 1
  id: string // an NSID
  type: 'query' | 'procedure' | 'record' | 'token'
  revision?: number
  description?: string
  defs?: JSONSchema
  // if type == record
  key?: string
  record?: JSONSchema
  // if type == query or procedure
  parameters?: Record<string, XrpcParameter>
  input?: XrpcBody
  output?: XrpcBody
  errors?: XrpcError[]
}
```

-while [the spec](https://github.com/bluesky-social/atproto-website/blob/main/content/specs/lexicon.md?plain=1#L32-L38) defines `LexiconDoc` as:

```
interface LexiconDoc {
  lexicon: 1
  id: string // an NSID
  revision?: number
  description?: string
  defs: Record<string, LexUserType|LexArray|LexPrimitive|LexRef[]>
}
```

The JSON files I see in https://github.com/bluesky-social/atproto/tree/main/lexicons seem to follow the spec version.

**Comment by bnewbold** [comment]
We wrote a longer Lexicon "specification" doc, and have removed the small schema snippet from the Lexicon "guide".
