### ISSUE TITLE
[Feature request] Add a search 

### ISSUE THREAD

**Issue by LukyVj** [bluesky-social/atproto-website#57]
Hello! 

Having a search the a documentation website would be so helpful! I went ahead and did my own version of your doc with a [docsearch](https://docsearch.algolia.com/) on it. https://atproto-search.vercel.app/docs

If you'd like to have it up and running on [atproto](https://atproto.com/) it'll be a pleasure to help! 

Also having a docsearch is **free**! :)

**Comment by emilyliu7321** [comment]
thanks for the suggestion, we added search with #190 :)
