### ISSUE TITLE
pds build instructions

### ISSUE THREAD

**Issue by Evalprime** [bluesky-social/atproto-website#81]
could provide build instructions on how to make a pds in the docs somewhere, I had to manually figure out how the repo is set up to set up my own pds

**Comment by ianklatzco** [comment]
did you take notes? would be useful ^^

**Comment by Evalprime** [comment]
yes, here's what I did:
1. I cloned the main repo
2. I ran yarn install and that automatically built everything
3. I believe I moved the example file to where it's supposed to go and ran npm run start in the pds folder and then I encountered some error about a did method so, and this is the part I'm confused about, I somehow ran an application that ran on the did port? I believe it might have been in the actual did resolver repo
4. the pds said something about a postgres db so obviously I made a postgres db. I had to change the connection in the config so that it would accept all connections but I think that's just the distro I was using, rhel
5. I pointed nginx towards the pds port and everything just worked from there

**Comment by Evalprime** [comment]
> Those are all development examples. For real-world use you would want to point to the "real" DID PLC instance (see config defaults for that location/URL).

I didn't know about this. from what I'm reading, there's a central PLC instance? isn't that antithetical to decentralization? I did see a URL, https://plc.directory/, that seems to be what you're talking about. but ideally I should be able to resolve DIDs without using one central service

**Comment by bnewbold** [comment]
You can read more about the DID PLC specification and design here: https://github.com/bluesky-social/did-method-plc

In practical terms it is a centralized service, but control over identity is rooted in cryptographic keys. The directory can only violate trust in a few ways (mostly by omission), and it should be possible to run mirrors, monitor for manipulated responses, etc. We think this are reasonable trade-offs against the service being no-cost for registering accounts, resource efficient, and predictable in latency. Interested in moving it towards more of a consortium model with multiple redundant nodes and institutions involved.

We have a new repo with instructions on getting a PDS instance deploy over here: https://github.com/bluesky-social/pds

Going to close this issue now.
